"""JustAuth-style OAuth provider catalog for the desktop app.

This file defines the visible provider matrix and the subset that is already
adapted by the Python desktop stack. Providers without a working adapter still
show up in the UI, but remain disabled until their per-provider flow is added.
"""

from __future__ import annotations


def _p(label, category, auth_url="", token_url="", user_info_url="", scope="",
       implemented=False, profile_adapter="", docs_url="", extra_auth_params=None):
    return {
        "label": label,
        "category": category,
        "auth_url": auth_url,
        "token_url": token_url,
        "user_info_url": user_info_url,
        "scope": scope,
        "implemented": implemented,
        "profile_adapter": profile_adapter,
        "docs_url": docs_url,
        "extra_auth_params": extra_auth_params or {},
    }


OAUTH_PROVIDER_CATALOG = {
    "github": _p(
        "GitHub", "开发者",
        "https://github.com/login/oauth/authorize",
        "https://github.com/login/oauth/access_token",
        "https://api.github.com/user",
        "read:user user:email",
        True, "github", "https://github.com/settings/developers",
    ),
    "gitee": _p(
        "Gitee", "开发者",
        "https://gitee.com/oauth/authorize",
        "https://gitee.com/oauth/token",
        "https://gitee.com/api/v5/user",
        "user_info",
        True, "gitee", "https://gitee.com/oauth/applications",
    ),
    "gitlab": _p(
        "GitLab", "开发者",
        "https://gitlab.com/oauth/authorize",
        "https://gitlab.com/oauth/token",
        "https://gitlab.com/api/v4/user",
        "read_user",
        True, "gitlab", "https://gitlab.com/-/profile/applications",
    ),
    "google": _p(
        "Google", "国际",
        "https://accounts.google.com/o/oauth2/v2/auth",
        "https://oauth2.googleapis.com/token",
        "https://openidconnect.googleapis.com/v1/userinfo",
        "openid email profile",
        True, "google", "https://console.cloud.google.com/apis/credentials",
        {"access_type": "offline", "prompt": "select_account", "include_granted_scopes": "true"},
    ),
    "microsoft": _p(
        "Microsoft", "国际",
        "https://login.microsoftonline.com/common/oauth2/v2.0/authorize",
        "https://login.microsoftonline.com/common/oauth2/v2.0/token",
        "https://graph.microsoft.com/v1.0/me",
        "openid email profile User.Read",
        True, "microsoft", "https://portal.azure.com/",
    ),
    "linkedin": _p(
        "LinkedIn", "国际",
        "https://www.linkedin.com/oauth/v2/authorization",
        "https://www.linkedin.com/oauth/v2/accessToken",
        "https://api.linkedin.com/v2/userinfo",
        "openid profile email",
        True, "linkedin", "https://www.linkedin.com/developers/apps",
    ),
    "facebook": _p(
        "Facebook", "国际",
        "https://www.facebook.com/v19.0/dialog/oauth",
        "https://graph.facebook.com/v19.0/oauth/access_token",
        "https://graph.facebook.com/me?fields=id,name,email,picture",
        "public_profile email",
        True, "facebook", "https://developers.facebook.com/apps/",
    ),
    "weibo": _p(
        "微博", "国内",
        "https://api.weibo.com/oauth2/authorize",
        "https://api.weibo.com/oauth2/access_token",
        "https://api.weibo.com/2/users/show.json",
        "",
        False, "weibo", "https://open.weibo.com/",
    ),
    "dingtalk": _p(
        "钉钉", "国内",
        "https://login.dingtalk.com/oauth2/auth",
        "https://api.dingtalk.com/v1.0/oauth2/userAccessToken",
        "https://api.dingtalk.com/v1.0/contact/users/me",
        "openid",
        False, "dingtalk", "https://open.dingtalk.com/",
    ),
    "baidu": _p(
        "百度", "国内",
        "https://openapi.baidu.com/oauth/2.0/authorize",
        "https://openapi.baidu.com/oauth/2.0/token",
        "",
        "basic",
        False, "baidu", "https://developer.baidu.com/",
    ),
    "coding": _p(
        "Coding", "开发者",
        "https://coding.net/oauth_authorize.html",
        "https://coding.net/api/oauth/access_token",
        "",
        "user",
        False, "coding", "https://coding.net/",
    ),
    "oschina": _p(
        "开源中国", "开发者",
        "https://www.oschina.net/action/oauth2/authorize",
        "https://www.oschina.net/action/openapi/token",
        "https://www.oschina.net/action/openapi/user",
        "user_info",
        False, "oschina", "https://www.oschina.net/openapi",
    ),
    "alipay": _p(
        "支付宝", "国内",
        "https://openauth.alipay.com/oauth2/publicAppAuthorize.htm",
        "https://openapi.alipay.com/gateway.do",
        "",
        "auth_user",
        False, "alipay", "https://open.alipay.com/",
    ),
    "qq": _p(
        "QQ", "国内",
        "https://graph.qq.com/oauth2.0/authorize",
        "https://graph.qq.com/oauth2.0/token",
        "https://graph.qq.com/user/get_user_info",
        "get_user_info",
        False, "qq", "https://connect.qq.com/",
    ),
    "wechat_open": _p(
        "微信开放平台", "国内",
        "https://open.weixin.qq.com/connect/qrconnect",
        "https://api.weixin.qq.com/sns/oauth2/access_token",
        "https://api.weixin.qq.com/sns/userinfo",
        "snsapi_login",
        False, "wechat_open", "https://open.weixin.qq.com/",
    ),
    "taobao": _p(
        "淘宝", "国内",
        "https://oauth.taobao.com/authorize",
        "https://oauth.taobao.com/token",
        "",
        "user_info",
        False, "taobao", "https://open.taobao.com/",
    ),
    "douyin": _p(
        "抖音", "国内",
        "https://open.douyin.com/platform/oauth/connect",
        "https://open.douyin.com/oauth/access_token/",
        "https://open.douyin.com/oauth/userinfo/",
        "user_info",
        False, "douyin", "https://developer.open-douyin.com/",
    ),
    "xiaomi": _p(
        "小米", "国内",
        "https://account.xiaomi.com/oauth2/authorize",
        "https://account.xiaomi.com/oauth2/token",
        "",
        "profile",
        False, "xiaomi", "https://dev.mi.com/",
    ),
    "toutiao": _p(
        "今日头条", "国内",
        "",
        "",
        "",
        "",
        False, "toutiao", "https://open.toutiao.com/",
    ),
    "teambition": _p(
        "Teambition", "协作",
        "https://account.teambition.com/oauth2/authorize",
        "https://account.teambition.com/oauth2/access_token",
        "",
        "profile",
        False, "teambition", "https://open.teambition.com/",
    ),
    "stack_overflow": _p(
        "StackOverflow", "开发者",
        "https://stackoverflow.com/oauth",
        "https://stackoverflow.com/oauth/access_token/json",
        "https://api.stackexchange.com/2.3/me?site=stackoverflow",
        "no_expiry",
        False, "stack_overflow", "https://stackapps.com/apps/oauth/register",
    ),
    "pinterest": _p(
        "Pinterest", "国际",
        "https://www.pinterest.com/oauth/",
        "https://api.pinterest.com/v5/oauth/token",
        "https://api.pinterest.com/v5/user_account",
        "user_accounts:read",
        False, "pinterest", "https://developers.pinterest.com/",
    ),
    "renren": _p(
        "人人", "国内",
        "",
        "",
        "",
        "",
        False, "renren", "",
    ),
    "huawei": _p(
        "华为", "国内",
        "https://oauth-login.cloud.huawei.com/oauth2/v3/authorize",
        "https://oauth-login.cloud.huawei.com/oauth2/v3/token",
        "https://account.cloud.huawei.com/rest.php?nsp_svc=OpenUP.User.getInfo",
        "openid profile email",
        False, "huawei", "https://developer.huawei.com/consumer/cn/",
    ),
    "wecom": _p(
        "企业微信", "国内",
        "https://open.work.weixin.qq.com/wwopen/sso/qrConnect",
        "https://qyapi.weixin.qq.com/cgi-bin/gettoken",
        "",
        "snsapi_base",
        False, "wecom", "https://developer.work.weixin.qq.com/",
    ),
    "twitter": _p(
        "Twitter / X", "国际",
        "https://twitter.com/i/oauth2/authorize",
        "https://api.twitter.com/2/oauth2/token",
        "https://api.twitter.com/2/users/me",
        "tweet.read users.read offline.access",
        False, "twitter", "https://developer.x.com/",
    ),
    "feishu": _p(
        "飞书", "协作",
        "https://accounts.feishu.cn/open-apis/authen/v1/authorize",
        "https://open.feishu.cn/open-apis/authen/v1/access_token",
        "https://open.feishu.cn/open-apis/authen/v1/user_info",
        "contact:user.base:readonly",
        False, "feishu", "https://open.feishu.cn/",
    ),
    "slack": _p(
        "Slack", "协作",
        "https://slack.com/oauth/v2/authorize",
        "https://slack.com/api/oauth.v2.access",
        "https://slack.com/api/users.identity",
        "identity.basic identity.email identity.avatar",
        False, "slack", "https://api.slack.com/apps",
    ),
    "line": _p(
        "LINE", "国际",
        "https://access.line.me/oauth2/v2.1/authorize",
        "https://api.line.me/oauth2/v2.1/token",
        "https://api.line.me/v2/profile",
        "profile openid email",
        False, "line", "https://developers.line.biz/",
    ),
    "amazon": _p(
        "Amazon", "国际",
        "https://www.amazon.com/ap/oa",
        "https://api.amazon.com/auth/o2/token",
        "https://api.amazon.com/user/profile",
        "profile",
        False, "amazon", "https://developer.amazon.com/",
    ),
}


VISIBLE_PROVIDER_ORDER = [
    "google", "github", "gitee", "gitlab", "microsoft", "linkedin", "facebook",
    "weibo", "dingtalk", "baidu", "coding", "oschina", "alipay", "qq",
    "wechat_open", "taobao", "douyin", "xiaomi", "toutiao", "teambition",
    "stack_overflow", "pinterest", "renren", "huawei", "wecom", "twitter",
    "feishu", "slack", "line", "amazon",
]
