// This file is automatically generated. Do not edit it directly.
// Powered by EnterCloud Managed Supabase
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://spb-t4no004xn2xk4tj3.supabase.opentrust.net";
const SUPABASE_PUBLISHABLE_KEY = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiYW5vbiIsInJlZiI6InNwYi10NG5vMDA0eG4yeGs0dGozIiwiaXNzIjoic3VwYWJhc2UiLCJpYXQiOjE3ODEyNTUzNDgsImV4cCI6MjA5NjgzMTM0OH0.H99TRiAPXlSHvb_wrfKkgzqXysPc7hB4Yw1L-YdSp0A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
